server:
  port: 8085
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: feign
feign:
  hystrix:
    enabled: true